# 1. Utiliser la même image de base Python que l'API
FROM python:3.10-slim

# 2. Définir le répertoire de travail
WORKDIR /app

# 3. Installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copier l'ensemble du code
COPY . .

# 5. Exposer le port par défaut de Streamlit
EXPOSE 8501

# 6. Commande pour démarrer l'interface utilisateur
CMD ["streamlit", "run", "app/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]